### ISSUE TITLE
Slice Creation failed!!!

### ISSUE THREAD

**Issue by regek** [free5gmano/free5gmano#13]
I was able to install orchestrator but it failed the last step when it tries to do the allocation.
Setup: 
NM (free5gmano) - 192.168.3.30:30888/8000
NFVO - Kubernetes 192.168.3.30 -  I think this might be incorrect but not sure/ is it supposed to be same as NM or something different? 
`Create Network service descriptor...

/data/nm/NSD/989fa897-3e28-4688-9191-efca2c13eba4.zip

Upload 989fa897-3e28-4688-9191-efca2c13eba4.zip descriptor file...

Upload operated status 202

Network service descriptor ID: 2116fd24-83f2-416b-bf3c-ca1964793aqq

Create Network service Instance ...

Traceback (most recent call last):
  File "/home/mano/free5gmano/nssmf/plugin/kube5gnfvo/allocate/main.py", line 163, in <module>
    main()

  File "/home/mano/free5gmano/nssmf/plugin/kube5gnfvo/allocate/main.py", line 159, in main
    nfvo_plugin.allocate_nssi()

  File "/home/mano/.local/lib/python3.6/site-packages/service_mapping_plugin_framework/allocate_nssi_abc.py", line 65, in allocate_nssi
    self.ns_instance_instantiation()

  File "/home/mano/.local/lib/python3.6/site-packages/service_mapping_plugin_framework/allocate_nssi_abc.py", line 36, in ns_instance_instantiation
    self.create_ns_instance(self.ns_template_path)

  File "/home/mano/free5gmano/nssmf/plugin/kube5gnfvo/allocate/main.py", line 141, in create_ns_instance
    raise Exception(response)

Exception: {'attributeListOut': {'create_nsi': 500}, 'status': 'OperationFailed'}`

**Comment by regek** [comment]
On further investigation there is a problem in nfvo not sure how to resolve this or which component is causing the issue.

> Internal Server Error: /nslcm/v1/ns_instances/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/etcd3/client.py", line 46, in handler
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/etcd3/client.py", line 306, in get_prefix_response
    metadata=self.metadata
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1588443597.963693130","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3981,"referenced_errors":[{"created":"@1588443597.963683804","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":394,"grpc_status":14}]}"
>

**Comment by tw0927041027** [comment]
Hi regek,
Please make sure that an etcd service is valid in Kubernetes.
If you are not sure whether it works for kube5gnfvo, you can try using the service name, dual-network-nic-etcd-cluster-client.default.svc.cluster.local, on nsLookup.

**Comment by regek** [comment]
Thanks. 
it seems dual-network-nic-etcd-cluster-client.default.svc.cluster.local was not working so I had to update the client file with the IP address and port for the etcd client in kube5gnfvo
