### ISSUE TITLE
The Following Error ocurrs when trying to tun the following: python manage.py makemigrations nssmf moi

### ISSUE THREAD

**Issue by dcrowley-Onis** [free5gmano/free5gmano#28]
No installed app with label 'moi'.

I updated multiple python files but the issue remains the same

**Comment by dcrowley-Onis** [comment]
I fixed/patched  this issue myself.
 
The installation instructions miss the installation of some models through pip. Once installed the extra models were installed the script progressed but still failed with the error below. I've opened a new issue regarding this new problem and how I fixed it to get step 7 of the manual install to finish  
- python manage.py makemigrations nssmf moi
- python manage.py migrate

test@test-VirtualBox:~/free5gmano$ python manage.py makemigrations nssmf moi
Traceback (most recent call last):
  File "manage.py", line 37, in <module>
    main()
  File "manage.py", line 33, in main
    execute_from_command_line(sys.argv)
  File "/home/test/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_l            ine
    utility.execute()
  File "/home/test/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/test/.local/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/test/.local/lib/python3.6/site-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/home/test/.local/lib/python3.6/site-packages/django/core/management/base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/test/.local/lib/python3.6/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/test/.local/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/test/.local/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/test/.local/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/test/.local/lib/python3.6/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/test/.local/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/test/.local/lib/python3.6/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/test/.local/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/test/.local/lib/python3.6/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/test/free5gmano/free5gmano/urls.py", line 63, in <module>
    path('', include('moi.urls')),
  File "/home/test/.local/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/test/free5gmano/moi/urls.py", line 4, in <module>
    from moi.views import ObjectManagement
  File "/home/test/free5gmano/moi/views.py", line 10, in <module>
    from moi.serializers import *
  File "/home/test/free5gmano/moi/serializers.py", line 18, in <module>
    from moi.models import OtherFunction
ImportError: cannot import name 'OtherFunction'

**Comment by Samcandy** [comment]
Hi, dcrowley-Onis this question is 'OtherFunction' table not in models.py file. This question has been updated to the new version. Thank you for your issue.
