### ISSUE TITLE
OperationFailed

### ISSUE THREAD

**Issue by Omwalid** [free5gmano/free5gmano#55]
when running 
nmctl register plugin kube5gnfvo -f simpleexampleplugin/
OperationFailed

In simpleexampleplugin/config.yaml
nm_ip: "freef5mano_Service_ip:8000"
nfvo_ip: "kube5gnfvo_service_ip:8000"

is the config correct ? Why OperationFailed ?

**Comment by yanyan8566** [comment]
Hi @Omwalid 

This issues had been fix in branch "v2.0.0" and "v1.0.0" , please try it again , thank you.

**Comment by Omwalid** [comment]
Hi,
I tried again, I received the same issue
when kubectl logs free5mano-pod :
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 497, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 457, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 468, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 494, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/free5gmano/nssmf/views.py", line 673, in register_plugin
    with zipfile.ZipFile(request.data['file'].file) as zip_file:
  File "/usr/local/lib/python3.5/dist-packages/django/utils/datastructures.py", line 80, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'file'
[04/Mar/2021 16:56:11] "POST /plugin/management/ HTTP/1.1" 500 16478
Internal Server Error: /plugin/management/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/utils/datastructures.py", line 78, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 497, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 457, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 468, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 494, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/free5gmano/nssmf/views.py", line 673, in register_plugin
    with zipfile.ZipFile(request.data['file'].file) as zip_file:
  File "/usr/local/lib/python3.5/dist-packages/django/utils/datastructures.py", line 80, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'file'
[04/Mar/2021 16:57:36] "POST /plugin/management/ HTTP/1.1" 500 16478

Thank you for your help

________________________________
De : yanyan8566 <notifications@github.com>
Envoyé : jeudi 4 mars 2021 10:33
À : free5gmano/free5gmano <free5gmano@noreply.github.com>
Cc : Ougherb Mohammed Walid <walas19992010@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [free5gmano/free5gmano] OperationFailed (#55)


Hi @Omwalid<https://github.com/Omwalid>

This issues had been fix in branch "v2.0.0" and "v1.0.0" , please try it again , thank you.

**Comment by yanyan8566** [comment]
Hi
The free5gmano on Kubernetes have some bug.
We'll fix it recently.
Sorry about that.
Please try to manual install free5gmano and try it again , thank you.
However you can try the container image "u8566789/free5gmano-develop:v1" to
deploy free5gmano on Kubernetes.

Wish this help you.

Ougherb Mohammed Walid <notifications@github.com> 於 2021年3月5日 週五 上午1:06寫道：
